export const DURATION = 15;
export const DURATION_MOVE_UP_PERCENT = 0.4;
export const PALM_LOWEST_POSITION = -120;
export const PALM_HIGHEST_POSITION = 0;
export const CAMERA_LOOK_FORWARD = 0.02;
export const CAMERA_LOWEST_POSITION_LOOKAT = 0;
export const CAMERA_HIGHEST_POSITION_LOOKAT = 100;
